# Generated by Django 3.2.6 on 2021-09-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_comment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comment',
        ),
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.ManyToManyField(to='instagram.Comment'),
        ),
    ]
